# Generated by Django 6.0.1 on 2026-02-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_hackathonteam_hackathonparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='job',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.job'),
            preserve_default=False,
        ),
    ]
